import { Center, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo } from "react";
import axios from "axios";

import states from "../states.json";

interface InfoParmas {
  city: string;
  country: string;
  ip: string;
  loc: string;
  org: string;
  region: string;
  timezone: string;
}

interface InfoProps {
  info: InfoParmas;
}

const Home: NextPage<InfoProps> = ({ info }) => {
  const personInfo = info;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>This is the index page</p>
      </main>
    </>
  );
};

export default Home;
export async function getServerSideProps() {
  const res = await fetch("https://ipinfo.io/json", {
    headers: new Headers({
      Authorization: "Bearer " + "3f26802b4fde0f",
      "Content-Type": "application/x-www-form-urlencoded",
    }),
  });
  const info = await res.json();
  return {
    props: { info }, // will be passed to the page component as props
  };
}
